# JWT config
jwt:
  header: Authorization
  # this is test in open quant jwt, we need to handle jwt header data -> encode 하기 전 데이터 정보
  secret: dGhpcyBpcyB0ZXN0IGluIG9wZW4gcXVhbnQgand0LCB3ZSBuZWVkIHRvIGhhbmRsZSBqd3QgaGVhZGVyIGRhdGE=
  token-validity-in-seconds: 86400000 # 24 hours